### ISSUE TITLE
prepare changesheets for problematic triads in MongoDB

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-ontology#66]
possible dupe issue from another repo?

```yaml
problematic_env_broad_scale_term_ids:
- label: meadow ecosystem
  term: ENVO:00000108
- label: agriculture
  term: ENVO:01001442
problematic_env_medium_rm_ids:
- label: null
  term: FMA:14541
- label: plant-associated environment
  term: ENVO:01001001
```

## Leave as is
```yaml
env_broad_scale_term_ids:
- label: animal-associated environment
  term: ENVO:01001002
env_medium_rm_ids:
- label: portion of plant tissue
  term: PO:0009007
- label: leaf
  term: PO:0025034
```
